baseURL = "https://thinkerou.com/"
languageCode = "en-us"
title = "thinkerou"
theme = "swift"
author = "thinkerou"
canonifyurls = true
paginator = 8
menu = ["a", "b"]

[params]
staticman = false
googleAnalytics = "UA-42425385-1"
description = "在路上，永远年轻，永远热泪盈眶。"
disqusShortname = "thinkerou"

