baseURL = "https://thinkerou.com"
languageCode = "en-us"
title = "thinkerou"
theme = "swift"
author = "thinkerou"
canonifyurls = true
paginate = 4

[params]
staticman = false
googleAnalytics = "UA-42425385-1"
description = "在路上，永远年轻，永远热泪盈眶。"
disqusShortname = "thinkerou"

