baseURL = "https://thinkerou.com/"
languageCode = "en-us"
title = "thinkerou"
theme = "swift"
author = "thinkerou"
description = "在路上，永远年轻，永远热泪盈眶。"
canonifyurls = true
paginate = 4
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true

[params]
staticman = false
googleAnalytics = "UA-42425385-1"
disqusShortname = "thinkerou"

